"""Initial migration.

Revision ID: 5d1b38429301
Revises: 
Create Date: 2024-02-13 15:26:46.724988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1b38429301'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Set a default value for existing null emails
    op.execute('UPDATE "user" SET email = \'default@example.com\' WHERE email IS NULL')

    # Rest of the auto-generated commands
    op.create_table('chat_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('messages', sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)

    op.drop_table('chat_log')
    # ### end Alembic commands ###
